Tree UI
tomo1818/brainStormingApp pull request #7
Opened 2022-07-10 03:18 UTC by tk1225

型修正を行いeslintとtypescriptのエラーを解消しました。

package.jsonではWindowsに変更しています。
"lint": "eslint --ext \"src/**/*.{js,jsx,ts,tsx}\"",
    "format": "eslint --cache --fix \"src/**/*.{js,jsx,ts,tsx}\" && prettier --write \"src/**/*.{js,jsx,ts,tsx}\"",
    "fmt":"prettier --write \"src/**/*.{js,jsx,ts,tsx}\""

2022-07-10 10:29 UTC, tomo1818 requested changes
コメントしました。

2022-07-10 10:29 UTC, tomo1818 commented on src/components/NodeUI.tsx
> +  {item: Node, addList: addListType, deleteList: deleteListType}) {
propsの部分は
```suggestion
  NodeUI({ item, addList, deleteList }: Props
```
のようにするのが良いかと思います。

functionを定義する前に
```
type Props = {
  item: Node;
  addList: AddListType;
  deleteListType: DeleteListType;
}
```
のようにしておくとfunction内はすっきりします。

2022-07-10 10:29 UTC, tomo1818 commented on src/components/RecursiveTree.tsx
> +  {list: Node[], rootId: number, addList: addListType, deleteList: deleteListType}) {
上記のpropsのところと同じです。

2022-07-10 10:29 UTC, tomo1818 commented on src/pages/TestPage.tsx
> +    });
この部分ですがforEachにしたら
```
// eslint-disable-next-line array-callback-return
```
を削除してもエラーなくなったりしないですか？

map関数は基本返り値を持つものなので返り値を設定しない場合はforEachを使うみたいなことだったと記憶しています。（https://eslint.org/docs/latest/rules/array-callback-return）

2022-07-10 10:29 UTC, tomo1818 commented on src/pages/TestPage.tsx
> +    console.log('deleteList');
console.logは削除しておきましょう。

2022-07-10 10:29 UTC, tomo1818 commented on src/types/node.ts
> +export type deleteListType = (id: number, parentId: number) => void
prettierかけると上のNodeの部分と同じような形式になると思うのですがどうでしょうか？　　
Nodeの部分と同じ形で書くのが一般的かと思います。

Typeごとにファイル分けた方が見やすいかもです。  
他の人が見た時にnode.tsにAddListTypeとDeleteListTypeがあることがわからないかと思います。

2022-07-12 05:05 UTC, tomo1818 approved these changes
修正ありがとうございます🙇‍♂️

2022-07-14 01:37 UTC, Toshimaro approved these changes

2022-07-14 01:40 UTC, merged